// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeZqcWgftGIldKoGMU8Q0vU6tlAVWWkqU',
    appId: '1:944638894866:web:d5355c2305755b4f5c49cb',
    messagingSenderId: '944638894866',
    projectId: 'tracktasty-f6ad2',
    authDomain: 'tracktasty-f6ad2.firebaseapp.com',
    storageBucket: 'tracktasty-f6ad2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCegqoO-bRBghuQAjwnXfoluVi-PAF-c8Q',
    appId: '1:944638894866:android:1fc4c3155857843d5c49cb',
    messagingSenderId: '944638894866',
    projectId: 'tracktasty-f6ad2',
    storageBucket: 'tracktasty-f6ad2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC00a7m2SF8XLoB2hPYfd-0WsPTi3aJl2I',
    appId: '1:944638894866:ios:dbe4f60d9bc586785c49cb',
    messagingSenderId: '944638894866',
    projectId: 'tracktasty-f6ad2',
    storageBucket: 'tracktasty-f6ad2.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC00a7m2SF8XLoB2hPYfd-0WsPTi3aJl2I',
    appId: '1:944638894866:ios:dbe4f60d9bc586785c49cb',
    messagingSenderId: '944638894866',
    projectId: 'tracktasty-f6ad2',
    storageBucket: 'tracktasty-f6ad2.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeZqcWgftGIldKoGMU8Q0vU6tlAVWWkqU',
    appId: '1:944638894866:web:3e2fcdc01f7612395c49cb',
    messagingSenderId: '944638894866',
    projectId: 'tracktasty-f6ad2',
    authDomain: 'tracktasty-f6ad2.firebaseapp.com',
    storageBucket: 'tracktasty-f6ad2.firebasestorage.app',
  );
}